### ISSUE TITLE
assimp支持MMD模型

### ISSUE THREAD

**Issue by uicake** [HeisensOppings/LearnOpengl_Mingw#1]
教程那边评论被标记为垃圾信息了，申诉一个星期了也没反应，过来这边提个issue说一下哈
![image](https://github.com/HeisensOppings/LearnOpengl_Mingw/assets/23124754/f6e3a417-14a5-4181-9cc9-fdb76087ec20)

**Comment by HeisensOppings** [comment]
> 教程那边评论被标记为垃圾信息了，申诉一个星期了也没反应，过来这边提个issue说一下哈 ![image](https://user-images.githubusercontent.com/23124754/270591652-f6e3a417-14a5-4181-9cc9-fdb76087ec20.png)

感谢提醒，assimp可以加载pmx格式的模型，但是assimp似乎没法加载mmd模型的sph/spa toon的纹理，只有tex的纹理也就是(diffuse)纹理可以被加载，发现github的另一个开源的saba mmd的可以加载，但还在研究 ＞﹏＜

**Comment by uicake** [comment]
大佬加油！我还没学完OpenGL，到时候也看看，哈哈
